### ISSUE TITLE
Mail tracking breaks phpunit tests when using :memory:

### ISSUE THREAD

**Issue by Penthious** [jdavidbakr/mail-tracker#26]
When I run phpunit prior to installing mail-tracker I get all green, after I install mail tracker I get all red. I also tried to install it on a fresh install of laravel to see if I get the same error and sure enough I do. This is my phpunit.xml
```
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="database"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="MAIL_DRIVER" value="log"/>
    </php>
```

The error I get is 
```
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'message_id' on table 'sent_emails'.
```

**Comment by jdavidbakr** [comment]
Did you happen to upgrade from 2.0 or earlier at some point?  That sounds like you're missing a migration: https://github.com/jdavidbakr/mail-tracker/blob/master/database/migrations/2016_11_10_213551_add-message-id-to-sent-emails-table.php

**Comment by Penthious** [comment]
Negitive, So what I did was `laravel new app` then `composer require jdavidbakr/mail-tracker` did vendor publish and migrate. Now the strange thing is if I do my tests using my real database they work but if I switch it over to `:memory:` all tests break.
<img width="448" alt="screen shot 2017-05-04 at 10 59 06 pm" src="https://cloud.githubusercontent.com/assets/12500410/25734141/552c0556-311d-11e7-9186-08238ecc72da.png">

**Comment by jdavidbakr** [comment]
Is this still an issue?  The package itself is using :memory: as the DB driver and all tests are passing.

**Comment by jdavidbakr** [comment]
Due to lack of follow-up I am assuming this issue is resolved.

**Comment by MadMikeyB** [comment]
I'm also receiving this issue. It's because add-message-id-to-sent-emails-table migration is modifying multiple columns within a sqlite database which is [not supported by Laravel](https://laravel.com/docs/5.4/migrations).

>Dropping or modifying multiple columns within a single migration while using a SQLite database is not supported.

![screen shot 2017-07-25 at 13 37 44](https://user-images.githubusercontent.com/831828/28572324-79b00e02-713e-11e7-8626-d8161c6fe6da.jpg)

Thus this breaks unit tests where an in-memory SQLite database is used for the 'testing' environment.

For what it's worth I think that you could move this migration into two separate ones, or modify your original migration where you create the Sent Emails Table to add these columns there.

I know you have backwards-compatibility to think of though.

I hope this helps you track down the issue. :)

**Comment by jdavidbakr** [comment]
Fixed in https://github.com/jdavidbakr/mail-tracker/releases/tag/2.1.12
