### ISSUE TITLE
Not working on local host may i get some more detailed documentation 

### ISSUE THREAD

**Issue by 9meAhmed** [jdavidbakr/mail-tracker#41]
installed the package successfully emails are now storing in the DB but not updating when email is being opened or clicked

**Comment by jdavidbakr** [comment]
You can look in the source code of the emails to ensure that the links are properly being sent to your local system.  If the emails are being sent by an artisan command you'll want to make sure your APP_URL is set correctly.  You should be able to do some detective work to figure out what's happening by looking at the source of the emails.

Since this is not an issue with the package, I am closing this ticket.
