### ISSUE TITLE
CC'ing different emails on single email?

### ISSUE THREAD

**Issue by jab1000** [jdavidbakr/mail-tracker#45]
Any thoughts on what happens when the emails sent out have multiple people/emails CC'd on the email message being sent?

Used to use Mandrill and loved that it would give each CC email a separate tracking key by keeping all in an array of ids for a given "message".  We now use AWS SES and haven't been able to replicate this type of functionality yet - thoughts on this?

**Comment by jdavidbakr** [comment]
Mandrill was likely splitting the message up and sending individual copies - obviously you can't send a single message to multiple recipients via CC and insert a unique tracking code in each one.

**Comment by saloni-garg** [comment]
Can you explain how are you going to solve this issue of tracking multiple emails being CC'ed?

**Comment by jdavidbakr** [comment]
The only solution I can think of is to change your application where you are sending separate emails instead of one with multiple CC's.  Essentially, multiple CC'd emails is one email going to multiple destinations, and as such, cannot be tracked separately.

I suppose you could also write a handler that separates multiple CC'd emails into separate emails, which I would imagine is what Mandril is doing if they are tracking opens for each recipient separately.

**Comment by jab1000** [comment]
My hunch on Mandril was since they truly "managed" the individual sending of a CC'd message and had created/modified the "server" (vs just using postfix) they could include a tracking code just prior to sending and include a tracking header with it and made some type of relationship through all that for who specifically it was.

Post Mandrill and ONLY using SES, Here is how we are trying to do it:
1.  create a list of "userIDs" for those CC'd on the email and add as a custom header in SES -- urlencode(base64_encode(json_encode($msgObj)));  Yes, we also have another couple x-header with messageID and sender's userID.
2.  We have a listener on our "send" which grabs the SES-ID and stamps it into our message log.
3.  when "delivered" (ses hook), grab the custom headers to mark as delivered and stamp in SES-ID if needed
4.  We already have a separate custom tracking link we have used about a year+ and we work to match up "IPs" for different users and weed out the bots checking URLs to work to "decipher" the "userID" from the list of userIDs in the custom header.

Our method is FAR from perfect but only options we have come up with so far since certain messages our members want as a CC.   Also why I figured I would pose the question out here for other ideas and ways to make this work if possible even better.

**Comment by jdavidbakr** [comment]
I agree that your method does leave a lot of room for error - but if it works for you, great!  Since this really can't be a part of this package but instead needs to be a system-level design decision (splitting cc's out into separate emails is outside of the scope of this package) I'm going to close this ticket.
